# Generated by Django 5.0.3 on 2024-03-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('n_afiliado', models.CharField(max_length=20)),
                ('profesional', models.CharField(max_length=20)),
                ('fecha_estudio', models.DateField()),
            ],
        ),
    ]
