# Generated by Django 5.0.3 on 2024-04-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudio',
        ),
    ]
