# Generated by Django 5.0.3 on 2024-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='n_afiliado',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
