# Generated by Django 5.0.3 on 2024-03-28 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_paciente_n_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 13, 33, 46, 411797)),
            preserve_default=False,
        ),
    ]
