# Generated by Django 5.0.3 on 2024-04-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios_rx',
            name='imagen',
            field=models.ImageField(default='img', upload_to='estudios_img'),
            preserve_default=False,
        ),
    ]
