# Generated by Django 5.0.3 on 2024-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_medicos', '0002_estudios_rx_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_rx',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estudios_img'),
        ),
    ]
