# Generated by Django 5.0.3 on 2024-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_datosextras_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextras',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
