# Generated by Django 5.0.3 on 2024-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_datosextras_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextras',
            name='bio',
            field=models.CharField(default='Descripcion', max_length=20),
            preserve_default=False,
        ),
    ]
